"""empty message

Revision ID: 3cebc271c755
Revises: ecdd9c18627f
Create Date: 2022-02-13 14:02:23.429425

"""

# revision identifiers, used by Alembic.
revision = '3cebc271c755'
down_revision = 'ecdd9c18627f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
