"""empty message

Revision ID: ecdd9c18627f
Revises: None
Create Date: 2022-02-13 12:07:13.163199

"""

# revision identifiers, used by Alembic.
revision = 'ecdd9c18627f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
